# Generated by Django 2.2.5 on 2019-11-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191106_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=32, null=True, verbose_name='img'),
        ),
    ]
