# Generated by Django 2.2.5 on 2019-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(null=True, verbose_name='Последнее Сообщение'),
        ),
    ]
