# Generated by Django 2.2.5 on 2019-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_attachment', models.CharField(max_length=20, verbose_name='Тип Прикрепления')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Прикрепление',
                'verbose_name_plural': 'Прикрепления',
            },
        ),
    ]
