# Generated by Django 2.2.5 on 2019-11-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_attachment', models.CharField(max_length=12, verbose_name='Тип Прикрепления')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Прикрепление',
                'verbose_name_plural': 'Прикрепления',
            },
        ),
    ]
