# Generated by Django 2.2.5 on 2019-11-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_read_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.Message', verbose_name='Последнее прочитанное сообщение'),
        ),
    ]
