# Generated by Django 2.2.5 on 2019-11-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участиники'},
        ),
    ]
