# Generated by Django 2.2.5 on 2019-11-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
